apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apim-connector-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apim-connector-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: apim-eks-sa
  namespace: default
roleRef:
  kind: Role
  name: apim-connector-role
  apiGroup: rbac.authorization.k8s.io
